var MONTH_NAMES=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],pluralize=(e,n)=>e+" "+n+(e<=1?"":"s");function getTooltip(e,n){return n=new Date(n.getTime()-6e4*n.getTimezoneOffset()).toISOString().split("T")[0],e.count===0?"No writing on "+n:pluralize(e.post,"post")+` ${pluralize(e.count,"word")} on `+n}var heatmapTooltip=document.getElementById("heatmap-tooltip");function hideTooltip(){heatmapTooltip.style.display="none"}function tileClickHandler(e){let n=e.target;if(n.classList.contains("tile")){let s=(e=new Date(Number(n.dataset.date))).toISOString();var a=window.REIMU_HEATMAP_CONFIG.articleStats.filter(l=>l.date===s),o=n.dataset.level;e=e.toLocaleDateString();let v=0,u=`
    <div class="tooltip-header">
      <div class="tooltip-header-content">${e} (Level ${o})</div>
      <div class="popup-btn-close tooltip-close"></div>
    </div>
    <div class="tooltip-content">
      <ul>
  `,c=window.REIMU_HEATMAP_CONFIG.i18n,t=document.documentElement.lang||"en";Object.keys(c).includes(t)||(t="en"),a.length===0?u+=`<li>${c[t].no_articles}</li>`:a.forEach(l=>{v+=l.wordcount,u+=`<li><a href="${l.url}">${l.title}</a> (${l.wordcount} ${c[t].words})</li>`}),e=c[t].total_articles.replace("$1",a.length).replace("$2",v),u+=`
      </ul>
      <div class="tooltip-footer">
        ${e}
      </div>
    </div>
  `,heatmapTooltip.innerHTML=u,o=n.getBoundingClientRect(),heatmapTooltip.style.display="block",heatmapTooltip.style.visibility="hidden",heatmapTooltip.style.left="0px",e=(a=heatmapTooltip.getBoundingClientRect()).width;let r=o.right+10;r+e>window.innerWidth&&(r=o.left-e-10),heatmapTooltip.style.left=r+"px",heatmapTooltip.style.top=o.top+"px",heatmapTooltip.style.display="block",heatmapTooltip.style.visibility="visible",(a=heatmapTooltip.querySelector(".tooltip-close"))&&a.addEventListener("click",hideTooltip),document.addEventListener("click",function l(i){i.target.classList.contains("tile")||heatmapTooltip.contains(i.target)||i.target===n||(hideTooltip(),document.removeEventListener("click",l))})}}function createCalendar(e,n){if(!e)return;e.innerHTML=`
    <div class="outer-box">
      <div class="year-select"></div>
      <div class="inner-box">
        <div class="calendar-container">
          ${["Mon","Wed","Fri"].map(t=>`<span class="week">${t}</span>`).join("")}
          <div class="legend">Less${new Array(5).fill(0).map((t,r)=>`<i class="tile" data-level="${r}"></i>`).join("")}More</div>
          <div class="tiles"></div>
        </div>
      </div>
    </div>
  `;let a=e.querySelector(".calendar-container");var o=e.querySelector(".year-select");let s=e.querySelector(".tiles"),v=completeContributionData(n),u=new Date().getFullYear(),c=(o.innerHTML=Object.keys(v).sort((t,r)=>r-t).map(t=>`<div class="year-option ${t==u?"active":""}">${t}</div>`).join(""),o.addEventListener("click",({target:t})=>{t.classList.contains("year-option")&&(e.querySelector(".active")?.classList.remove("active"),t.classList.add("active"),c(t.textContent))}),t=>{s.innerHTML="",a.querySelectorAll(".month").forEach(m=>m.remove()),a.querySelectorAll(".total").forEach(m=>m.remove());var g=v[t];let r=new Date(g[0].date).getDay(),l=-1,i=document.createDocumentFragment();var M=document.createDocumentFragment();let D=-1;var[g,$]=g.reduce(([m,f],p,w)=>{var h=new Date(p.date),d=h.getMonth();if(f.count+=p.count,f.post+=p.post,h.getDay()===0&&d!==l){let y=2+Math.floor((w+r)/7);y-D<=1&&(y+=2-y+D),D=y,l=d,(w=document.createElement("span")).className="month",w.textContent=MONTH_NAMES[d],w.style.gridColumn=y,i.append(w)}return(d=document.createElement("i")).className="tile",d.dataset.level=p.level,d.title=getTooltip(p,h),d.dataset.level=p.level,d.dataset.date=p.date,d.addEventListener("click",tileClickHandler),m.push(d),[m,f]},[[],{count:0,post:0}]);g[0]&&(g[0].style.gridRow=r+1),M.append(...g),a.append(i),s.append(M),a.insertAdjacentHTML("beforeend",`<div class="total">${pluralize($.post,"post")} ${pluralize($.count,"word")} in ${t}</div>`)});c(u)}function completeContributionData(e){e.sort((l,i)=>l.date-i.date);var n=new Date(e[0].date),a=new Date,o={};let s={};e.forEach(l=>{var i=`${(i=new Date(l.date)).getFullYear()}-${i.getMonth()}-`+i.getDate();s[i]=l});for(let l=n.getFullYear();l<=a.getFullYear();l++){for(var[v,u]=l===a.getFullYear()?[new Date(new Date(a).setDate(a.getDate()-365)),new Date(a.getTime()+864e5)]:[new Date(l,0,1),new Date(l+1,0,1)],c=[],t=v;t<u;t.setDate(t.getDate()+1)){var r=`${t.getFullYear()}-${t.getMonth()}-`+t.getDate();c.push(s[r]||{level:0,date:t.getTime(),count:0,post:0})}o[l]=c}return o}function getLevelFromWordCount(e){var n=window.REIMU_HEATMAP_CONFIG.levelStandard.split(",").map(Number);return e<=0?0:e<=n[0]?1:e<=n[1]?2:e<=n[2]?3:4}var currentDate=new Date;function transformArticlesData(e){return e=e.reduce((n,{date:a,wordcount:o})=>{var s;return new Date(a)>currentDate?n:(s=n.get(a)??{count:0,post:0},n.set(a,{count:s.count+o,post:s.post+1}))},new Map),Array.from(e,([n,{count:a,post:o}])=>({level:getLevelFromWordCount(a),date:new Date(n).getTime(),count:a,post:o}))}createCalendar(document.querySelector("#heatmap"),transformArticlesData(window.REIMU_HEATMAP_CONFIG.articleStats));
