var MONTH_NAMES=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],pluralize=(e,n)=>e+" "+n+(e<=1?"":"s");function getTooltip(e,n){return n=new Date(n.getTime()-6e4*n.getTimezoneOffset()).toISOString().split("T")[0],e.count===0?"No writing on "+n:pluralize(e.post,"post")+` ${pluralize(e.count,"word")} on `+n}function createCalendar(e,n){if(!e)return;e.innerHTML=`
    <div class="outer-box">
      <div class="year-select"></div>
      <div class="inner-box">
        <div class="calendar-container">
          ${["Mon","Wed","Fri"].map(t=>`<span class="week">${t}</span>`).join("")}
          <div class="legend">Less${new Array(5).fill(0).map((t,i)=>`<i class="tile" data-level="${i}"></i>`).join("")}More</div>
          <div class="tiles"></div>
        </div>
      </div>
    </div>
  `;let a=e.querySelector(".calendar-container");var o=e.querySelector(".year-select");let s=e.querySelector(".tiles"),m=completeContributionData(n),g=new Date().getFullYear(),v=(o.innerHTML=Object.keys(m).sort((t,i)=>i-t).map(t=>`<div class="year-option ${t==g?"active":""}">${t}</div>`).join(""),o.addEventListener("click",({target:t})=>{t.classList.contains("year-option")&&(e.querySelector(".active")?.classList.remove("active"),t.classList.add("active"),v(t.textContent))}),t=>{s.innerHTML="",a.querySelectorAll(".month").forEach(u=>u.remove()),a.querySelectorAll(".total").forEach(u=>u.remove());var d=m[t];let i=new Date(d[0].date).getDay(),r=-1,l=document.createDocumentFragment();var f=document.createDocumentFragment(),[d,T]=d.reduce(([u,w],p,y)=>{var D,M=new Date(p.date),c=M.getMonth();return(c=(w.count+=p.count,w.post+=p.post,M.getDay()===0&&c!==r&&(y=2+Math.floor((y+i)/7),r=c,(D=document.createElement("span")).className="month",D.textContent=MONTH_NAMES[c],D.style.gridColumn=y,l.append(D)),document.createElement("i"))).className="tile",c.dataset.level=p.level,c.title=getTooltip(p,M),u.push(c),[u,w]},[[],{count:0,post:0}]);d[0]&&(d[0].style.gridRow=i+1),f.append(...d),a.append(l),s.append(f),a.insertAdjacentHTML("beforeend",`<div class="total">${pluralize(T.post,"post")} ${pluralize(T.count,"word")} in ${t}</div>`)});v(g)}function completeContributionData(e){e.sort((r,l)=>r.date-l.date);var n=new Date(e[0].date),a=new Date,o={};let s={};e.forEach(r=>{var l=`${(l=new Date(r.date)).getFullYear()}-${l.getMonth()}-`+l.getDate();s[l]=r});for(let r=n.getFullYear();r<=a.getFullYear();r++){for(var[m,g]=r===a.getFullYear()?[new Date(new Date(a).setDate(a.getDate()-365)),new Date(a.getTime()+864e5)]:[new Date(r,0,1),new Date(r+1,0,1)],v=[],t=m;t<g;t.setDate(t.getDate()+1)){var i=`${t.getFullYear()}-${t.getMonth()}-`+t.getDate();v.push(s[i]||{level:0,date:t.getTime(),count:0,post:0})}o[r]=v}return o}function getLevelFromWordCount(e){var n=window.REIMU_HEATMAP_CONFIG.levelStandard.split(",").map(Number);return e<=0?0:e<=n[0]?1:e<=n[1]?2:e<=n[2]?3:4}function transformArticlesData(e){return e=e.reduce((n,{date:a,wordcount:o})=>{var s=n.get(a)??{count:0,post:0};return n.set(a,{count:s.count+o,post:s.post+1})},new Map),Array.from(e,([n,{count:a,post:o}])=>({level:getLevelFromWordCount(a),date:new Date(n).getTime(),count:a,post:o}))}createCalendar(document.querySelector("#heatmap"),transformArticlesData(window.REIMU_HEATMAP_CONFIG.articleStats));
