(()=>{_$$("pre").forEach(e=>{var i,t=e.parentNode;t.classList.contains("gutter")||((i=document.createElement("div")).className="code-area",t.insertBefore(i,e),t.removeChild(e),i.appendChild(e))});let n=(window.REIMU_CONFIG?.code_block||{}).expand;if(_$$("figure.highlight").forEach(e=>{e.querySelector(".code-figcaption")||e.insertAdjacentHTML("afterbegin",`
  <div class="code-figcaption">
    <div class="code-left-wrap">
      <div class="code-decoration"></div>
      <div class="code-lang"></div>
    </div>
    <div class="code-right-wrap">
      <div class="code-copy icon-copy"></div>
      <div class="icon-chevron-down code-expand"></div>
    </div>
  </div>`),n!==void 0&&(n===!1||typeof n=="number"&&e.querySelectorAll("td.code .line").length>n)&&(e.classList.add("code-closed"),e.style.display="none",e.style.display="")}),_$$(".code-expand").forEach(e=>{e.off("click").on("click",()=>{e.closest("figure").classList.toggle("code-closed")})}),_$$("figure.highlight").forEach(e=>{var i=e.className.split(" ")[1];if(i){let t=i.replace("line-numbers","").trim().replace("language-","").trim();t=t.toUpperCase(),(i=e.querySelector(".code-lang"))&&(i.innerText=t)}}),window.ClipboardJS){let e=window.REIMU_CONFIG?.clipboard_tips||{},i=new ClipboardJS(".code-copy",{text:t=>{let o=(t=t.parentNode.parentNode.parentNode.querySelector("td.code"))?t.innerText:"";return e.copyright?.enable&&o.length>=e.copyright?.count?o+`

`+(e.copyright?.content??""):o}});i.on("success",t=>{t.trigger.classList.add("icon-check"),t.trigger.classList.remove("icon-copy");var o=e.success;let c="Copy successfully (*^\u25BD^*)";if(typeof o=="string")c=o;else if(typeof o=="object"){let r=document.documentElement.lang;var s=Object.keys(o).find(l=>l.toLowerCase()===r.toLowerCase());s&&o[s]&&(c=o[s])}_$("#copy-tooltip").innerText=c,_$("#copy-tooltip").style.opacity=1,setTimeout(()=>{_$("#copy-tooltip").style.opacity=0,t.trigger.classList.add("icon-copy"),t.trigger.classList.remove("icon-check")},1e3),t.clearSelection()}),i.on("error",t=>{t.trigger.classList.add("icon-times"),t.trigger.classList.remove("icon-copy");var o=e.fail;let c="Copy failed (\uFF9F\u22BF\uFF9F)\uFF82";if(typeof o=="string")c=o;else if(typeof o=="object"){let r=document.documentElement.lang;var s=Object.keys(o).find(l=>l.toLowerCase()===r.toLowerCase());s&&o[s]&&(c=o[s])}_$("#copy-tooltip").innerText=c,_$("#copy-tooltip").style.opacity=1,setTimeout(()=>{_$("#copy-tooltip").style.opacity=0,t.trigger.classList.add("icon-copy"),t.trigger.classList.remove("icon-times")},1e3)}),window.Pjax&&window.addEventListener("pjax:send",()=>{i.destroy()},{once:!0}),window.AOS&&AOS.refresh()}})();
